"""
Email utility module for sending career development plans via SMTP.

Reads SMTP configuration from environment variables and provides safe
wrappers that never raise exceptions, suitable for direct use from the UI.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import markdown


# ---------------------------------------------------------------------------
# Configuration helpers
# ---------------------------------------------------------------------------

def _get_smtp_config() -> dict:
    """Read SMTP settings from environment variables."""
    return {
        "host": os.getenv("SMTP_HOST", "smtp.gmail.com"),
        "port": int(os.getenv("SMTP_PORT", "587")),
        "user": os.getenv("SMTP_USER", ""),
        "password": os.getenv("SMTP_PASSWORD", ""),
        "from_name": os.getenv("SMTP_FROM_NAME", "AI Career Coach"),
    }


def is_email_configured() -> bool:
    """Return True if SMTP_USER and SMTP_PASSWORD are set in env."""
    cfg = _get_smtp_config()
    return bool(cfg["user"]) and bool(cfg["password"])


# ---------------------------------------------------------------------------
# Core send function
# ---------------------------------------------------------------------------

def send_plan_email(
    to_email: str,
    user_name: str,
    plan_markdown: str,
) -> tuple[bool, str]:
    """
    Send the career development plan to the user via email.

    Args:
        to_email: recipient email address.
        user_name: user's display name (used in the greeting).
        plan_markdown: the full plan in Markdown format.

    Returns:
        (success, message) -- ``True`` with a success note, or ``False``
        with a human-readable error description.

    The email is sent as multipart/alternative so clients that support HTML
    will render the rich version while plain-text clients fall back to the
    raw Markdown.
    """
    cfg = _get_smtp_config()

    # -- Build the plain-text body ------------------------------------------
    greeting = (
        f"Hi {user_name},\n\n"
        "Here is your personalized career development plan:\n\n"
    )
    footer = (
        "\n\n---\n"
        "Generated by AI Career Development & Performance Coach\n"
    )
    plain_body = greeting + plan_markdown + footer

    # -- Build the HTML body ------------------------------------------------
    html_greeting = (
        f"<p>Hi {user_name},</p>"
        "<p>Here is your personalized career development plan:</p>"
    )
    html_plan = markdown.markdown(
        plan_markdown,
        extensions=["tables", "fenced_code", "nl2br"],
    )
    html_footer = (
        '<hr style="margin-top:2em">'
        "<p><em>Generated by AI Career Development &amp; Performance Coach</em></p>"
    )
    html_body = (
        "<!DOCTYPE html>"
        '<html><head><meta charset="utf-8"></head><body>'
        f"{html_greeting}{html_plan}{html_footer}"
        "</body></html>"
    )

    # -- Assemble the MIME message ------------------------------------------
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Your 90-Day Career Development Plan"
    msg["From"] = f"{cfg['from_name']} <{cfg['user']}>"
    msg["To"] = to_email

    msg.attach(MIMEText(plain_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    # -- Send via SMTP ------------------------------------------------------
    with smtplib.SMTP(cfg["host"], cfg["port"], timeout=30) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(cfg["user"], cfg["password"])
        server.sendmail(cfg["user"], [to_email], msg.as_string())

    return True, f"Plan emailed successfully to {to_email}"


# ---------------------------------------------------------------------------
# Safe wrapper (UI entry-point)
# ---------------------------------------------------------------------------

def send_plan_email_safe(
    to_email: str,
    user_name: str,
    plan_markdown: str,
) -> tuple[bool, str]:
    """
    Wrapper around :func:`send_plan_email` that **never** raises.

    * Returns ``(False, "Email not configured...")`` when SMTP credentials
      are missing.
    * Catches every exception and returns ``(False, <error detail>)``
      instead of propagating.
    """
    if not is_email_configured():
        return (
            False,
            "Email not configured. Set SMTP_USER and SMTP_PASSWORD "
            "environment variables to enable email delivery.",
        )

    try:
        return send_plan_email(to_email, user_name, plan_markdown)
    except smtplib.SMTPAuthenticationError:
        return False, "SMTP authentication failed. Please check your SMTP_USER and SMTP_PASSWORD."
    except smtplib.SMTPRecipientsRefused:
        return False, f"Recipient address rejected: {to_email}"
    except smtplib.SMTPException as exc:
        return False, f"SMTP error: {exc}"
    except OSError as exc:
        return False, f"Network error (could not reach mail server): {exc}"
    except Exception as exc:
        return False, f"Unexpected error sending email: {exc}"
